# Generated by Django 5.2.7 on 2025-10-08 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_workcategory_code_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitoutchecklist',
            name='fitout_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='api.fitoutrequest'),
        ),
    ]
