# Generated by Django 5.2.7 on 2025-10-09 12:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_fitoutchecklist_fitout_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitoutrequest',
            name='user_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='fitoutrequestchat',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Association',
        ),
    ]
