# Generated by Django 5.2.7 on 2025-10-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fitoutrequest_user_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitoutguide',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
