# Generated by Django 5.2.7 on 2025-10-11 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fitoutguide_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='Annexure',
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='contractor_mobile',
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='contractor_name',
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='unit_costs',
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='user_ids',
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='work_category',
        ),
        migrations.AddField(
            model_name='deviationstatus',
            name='fitout_deviation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deviation_statuses', to='api.fitoutdeviation'),
        ),
        migrations.AddField(
            model_name='fitoutrequest',
            name='agree_guidelines',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fitoutrequest',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitoutrequest',
            name='approved_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitoutrequest',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fitoutrequest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fitoutrequest',
            name='preferred_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitoutrequest',
            name='preferred_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitoutrequest',
            name='requester_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fitoutrequest',
            name='scope',
            field=models.TextField(default='no description was provided', help_text='Description of renovation scope'),
        ),
        migrations.AddField(
            model_name='fitoutrequest',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='fitout_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_categories', to='api.fitoutrequest'),
        ),
        migrations.AlterField(
            model_name='fitoutrequest',
            name='flat_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fitoutrequest',
            name='tower_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(default='#000000', help_text='Hex color code, e.g. #00FF00', max_length=7),
        ),
    ]
