# Generated by Django 5.2.7 on 2025-10-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_status_name_alter_status_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitoutchecklist',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='flat_id',
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='floor_id',
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='oneBHK',
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='oneBHK_RK',
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='oneBHK_again',
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='tower_id',
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='twoBHK',
        ),
        migrations.RemoveField(
            model_name='fitoutrequest',
            name='twoBHK_TERRIS',
        ),
        migrations.AddField(
            model_name='workcategory',
            name='flat_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='oneBHK',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='oneBHK_RK',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='oneBHK_again',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='tower_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='twoBHK',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='twoBHK_TERRIS',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
