# Generated by Django 5.2.7 on 2025-10-13 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='WorkCategory',
        ),
        migrations.RemoveField(
            model_name='annexure',
            name='category',
        ),
        migrations.AddField(
            model_name='annexure',
            name='WorkCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Annexures', to='api.workcategory'),
        ),
        migrations.AddField(
            model_name='fitoutchecklist',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitout_checklists', to='api.subcategory'),
        ),
        migrations.DeleteModel(
            name='CategoryAnnexure',
        ),
    ]
