# Generated by Django 5.2.7 on 2025-10-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_category_subcategory_workcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitoutchecklist',
            name='associations',
        ),
        migrations.RemoveField(
            model_name='fitoutchecklist',
            name='category',
        ),
        migrations.AddField(
            model_name='fitoutchecklist',
            name='work_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitout_checklists', to='api.workcategory'),
        ),
    ]
