# Generated by Django 5.2.7 on 2025-10-15 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_fitoutchecklist_associations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistanswer',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='checklistanswer',
            name='question_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_answers', to='api.questionoption'),
        ),
        migrations.AlterField(
            model_name='checklistanswer',
            name='fitout_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_answers', to='api.fitoutrequest'),
        ),
        migrations.AlterField(
            model_name='checklistanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_answers', to='api.checklistquestion'),
        ),
    ]
