# Generated by Django 5.2.7 on 2025-10-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_checklistanswer_selected_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workcategory',
            name='flat_id',
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='oneBHK',
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='oneBHK_RK',
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='oneBHK_again',
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='tower_id',
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='twoBHK',
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='twoBHK_TERRIS',
        ),
    ]
