# Generated by Django 5.2.7 on 2025-10-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_workcategory_flat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('flat_type', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('movein_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('gate_pass_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('movein_status', models.CharField(blank=True, max_length=50, null=True)),
                ('movein_status_options', models.JSONField(blank=True, default=list, help_text="List of possible move-in statuses, e.g., ['PENDING','APPROVED','REJECTED','MOVED_IN']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fitout Type',
                'verbose_name_plural': 'Fitout Types',
                'db_table': 'fitout_types',
                'ordering': ['name'],
            },
        ),
    ]
